[package]
name = "tokio-simplified"
version = "0.1.2"
authors = ["Pierre Avital <pierre.avital+gitlab@gmail.com>"]
edition = "2018"
description = "A simplified API to interract with tokio sinks and streams"
license = "Apache-2.0"

[dependencies]
futures = "0.1.26"
tokio = "0.1.18"
bytes = ""